name: RuneForgedWarzone
version: '1.0'
main: com.hasangarh.runeforgedwarzone.RuneForgedWarzone
api-version: '1.21'
authors: [zVortexLabs]
depend:
  - WorldGuard
  - RuneForgedRunes
description: Warzone plugin for RuneForged Survival by GauravBuilds
commands:
  warzone:
    description: Main warzone admin command.
    permission: warzone.admin
    usage: /warzone <setaltar|spawnboss|drop>
  bounty:
    description: View or set bounties on players.
    usage: /bounty [player] [amount]